version: '3.3'
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    networks:
      - ci_net
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - "jenkins:/var/jenkins_home"

  artifactory:
    image: "docker.bintray.io/jfrog/artifactory-oss:latest"
    networks:
      - ci_net
    ports:
      - "8086:8081"
    volumes:
      - "/Users/gs/arty:/var/opt/jfrog/artifactory"


volumes:
  jenkins:
networks:
  ci_net: