pipeline {
    node any
    triggers {
        GenericTrigger(
            genericVariables: [
                [key: 'ARTIFACT_NAME', value: '$.artifactory.webhook.data.name'],
                [event: 'EVENT_NAME',  value: '$.artifactory.webhook.event']
            ],
            causeString: 'Triggered on $ARTIFACT_NAME',

            regexpFilterText: '$EVENT_NAME-$ARTIFACT_NAME',
            regexpFilterExpression: 'storage\.afterCreate-SuperPackage'
    	    )
	}

}